# Arquivo de configuração do Decap CMS

backend:
  name: git-gateway
  branch: main

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Data de Publicação", name: "pubDate", widget: "datetime" }
      - { label: "Descrição Curta", name: "description", widget: "string" }
      - { label: "Autor", name: "author", widget: "string", default: "Lucas" }
      - { label: "Imagem de Capa", name: "image", widget: "image" }
      - { label: "Tags (separadas por vírgula)", name: "tags", widget: "string" }
      - { label: "Conteúdo do Post", name: "body", widget: "markdown" }